# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3774302d02fb9682e46804f1dbbabeea4e0ec9a6e8b567883d1dd5a3eb2b2f83354e5929069c54382bb3d7a8c67c9debfd65ef2e039b8000778841a6f022beb3

test:
  secret_key_base: 5c54ad566302cdcfa3dca76a37f1542cb44133e3a53855c7119da662a2d2d140f5ab263487f815a9e6c496c79d73246b979dc2d21ca1a878c7d2f6d5eadafdbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
